name: CI_CD

on:
  push:
    branches: [ feature-inicial, main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt || echo "Sem dependências"
      - name: Run tests
        run: python -m unittest discover -s tests

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy simulation
        run: echo "Deploy realizado com sucesso!"
